[users.admin]
name = "CreditGuard Administrator"
password_hash = "$2b$12$tHu0RHng3FjrXxCVBVPuX.vGETLZomCYK7o45NMlTJrfXSb4eks1W"
role = "Admin"

[users.analyst]
name = "Credit Risk Analyst"
password_hash = "$2b$12$c9/IilVMR3N3Qxrn1uhcyuIgjFsAzII0sg6aD7Ln/QvSr.62WuA7O"
role = "Analyst"
